### ISSUE TITLE
Create profile

### ISSUE THREAD

**Issue by CrossyChainsaw** [CrossyChainsaw/TeammateTinder#3]
### Tasks
- [ ] Create profile from the frontend
- [ ] Create profile data in the backend
- [ ] Save profile data to database
